name: Pytest

on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test_package:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .[dev]

      - name: Run tests
        run: |
          pytest

      - name: Goodbye
        run: echo "Tests complete."
